// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WaringService.proto

package WarningService;

/**
 * Protobuf type {@code WarningService.WarningServiceRequest}
 */
public  final class WarningServiceRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:WarningService.WarningServiceRequest)
    WarningServiceRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use WarningServiceRequest.newBuilder() to construct.
  private WarningServiceRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private WarningServiceRequest() {
    patient_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private WarningServiceRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              patient_ = new java.util.ArrayList<WarningService.Patient>();
              mutable_bitField0_ |= 0x00000001;
            }
            patient_.add(
                input.readMessage(WarningService.Patient.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        patient_ = java.util.Collections.unmodifiableList(patient_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return WarningService.WarningServiceImpl.internal_static_WarningService_WarningServiceRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return WarningService.WarningServiceImpl.internal_static_WarningService_WarningServiceRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            WarningService.WarningServiceRequest.class, WarningService.WarningServiceRequest.Builder.class);
  }

  public static final int PATIENT_FIELD_NUMBER = 1;
  private java.util.List<WarningService.Patient> patient_;
  /**
   * <code>repeated .WarningService.Patient patient = 1;</code>
   */
  public java.util.List<WarningService.Patient> getPatientList() {
    return patient_;
  }
  /**
   * <code>repeated .WarningService.Patient patient = 1;</code>
   */
  public java.util.List<? extends WarningService.PatientOrBuilder> 
      getPatientOrBuilderList() {
    return patient_;
  }
  /**
   * <code>repeated .WarningService.Patient patient = 1;</code>
   */
  public int getPatientCount() {
    return patient_.size();
  }
  /**
   * <code>repeated .WarningService.Patient patient = 1;</code>
   */
  public WarningService.Patient getPatient(int index) {
    return patient_.get(index);
  }
  /**
   * <code>repeated .WarningService.Patient patient = 1;</code>
   */
  public WarningService.PatientOrBuilder getPatientOrBuilder(
      int index) {
    return patient_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < patient_.size(); i++) {
      output.writeMessage(1, patient_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < patient_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, patient_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof WarningService.WarningServiceRequest)) {
      return super.equals(obj);
    }
    WarningService.WarningServiceRequest other = (WarningService.WarningServiceRequest) obj;

    boolean result = true;
    result = result && getPatientList()
        .equals(other.getPatientList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getPatientCount() > 0) {
      hash = (37 * hash) + PATIENT_FIELD_NUMBER;
      hash = (53 * hash) + getPatientList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static WarningService.WarningServiceRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static WarningService.WarningServiceRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static WarningService.WarningServiceRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static WarningService.WarningServiceRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static WarningService.WarningServiceRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static WarningService.WarningServiceRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static WarningService.WarningServiceRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static WarningService.WarningServiceRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static WarningService.WarningServiceRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static WarningService.WarningServiceRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static WarningService.WarningServiceRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static WarningService.WarningServiceRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(WarningService.WarningServiceRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code WarningService.WarningServiceRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:WarningService.WarningServiceRequest)
      WarningService.WarningServiceRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return WarningService.WarningServiceImpl.internal_static_WarningService_WarningServiceRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return WarningService.WarningServiceImpl.internal_static_WarningService_WarningServiceRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              WarningService.WarningServiceRequest.class, WarningService.WarningServiceRequest.Builder.class);
    }

    // Construct using WarningService.WarningServiceRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getPatientFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (patientBuilder_ == null) {
        patient_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        patientBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return WarningService.WarningServiceImpl.internal_static_WarningService_WarningServiceRequest_descriptor;
    }

    @java.lang.Override
    public WarningService.WarningServiceRequest getDefaultInstanceForType() {
      return WarningService.WarningServiceRequest.getDefaultInstance();
    }

    @java.lang.Override
    public WarningService.WarningServiceRequest build() {
      WarningService.WarningServiceRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public WarningService.WarningServiceRequest buildPartial() {
      WarningService.WarningServiceRequest result = new WarningService.WarningServiceRequest(this);
      int from_bitField0_ = bitField0_;
      if (patientBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          patient_ = java.util.Collections.unmodifiableList(patient_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.patient_ = patient_;
      } else {
        result.patient_ = patientBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof WarningService.WarningServiceRequest) {
        return mergeFrom((WarningService.WarningServiceRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(WarningService.WarningServiceRequest other) {
      if (other == WarningService.WarningServiceRequest.getDefaultInstance()) return this;
      if (patientBuilder_ == null) {
        if (!other.patient_.isEmpty()) {
          if (patient_.isEmpty()) {
            patient_ = other.patient_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePatientIsMutable();
            patient_.addAll(other.patient_);
          }
          onChanged();
        }
      } else {
        if (!other.patient_.isEmpty()) {
          if (patientBuilder_.isEmpty()) {
            patientBuilder_.dispose();
            patientBuilder_ = null;
            patient_ = other.patient_;
            bitField0_ = (bitField0_ & ~0x00000001);
            patientBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPatientFieldBuilder() : null;
          } else {
            patientBuilder_.addAllMessages(other.patient_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      WarningService.WarningServiceRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (WarningService.WarningServiceRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<WarningService.Patient> patient_ =
      java.util.Collections.emptyList();
    private void ensurePatientIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        patient_ = new java.util.ArrayList<WarningService.Patient>(patient_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        WarningService.Patient, WarningService.Patient.Builder, WarningService.PatientOrBuilder> patientBuilder_;

    /**
     * <code>repeated .WarningService.Patient patient = 1;</code>
     */
    public java.util.List<WarningService.Patient> getPatientList() {
      if (patientBuilder_ == null) {
        return java.util.Collections.unmodifiableList(patient_);
      } else {
        return patientBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .WarningService.Patient patient = 1;</code>
     */
    public int getPatientCount() {
      if (patientBuilder_ == null) {
        return patient_.size();
      } else {
        return patientBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .WarningService.Patient patient = 1;</code>
     */
    public WarningService.Patient getPatient(int index) {
      if (patientBuilder_ == null) {
        return patient_.get(index);
      } else {
        return patientBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .WarningService.Patient patient = 1;</code>
     */
    public Builder setPatient(
        int index, WarningService.Patient value) {
      if (patientBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePatientIsMutable();
        patient_.set(index, value);
        onChanged();
      } else {
        patientBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .WarningService.Patient patient = 1;</code>
     */
    public Builder setPatient(
        int index, WarningService.Patient.Builder builderForValue) {
      if (patientBuilder_ == null) {
        ensurePatientIsMutable();
        patient_.set(index, builderForValue.build());
        onChanged();
      } else {
        patientBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .WarningService.Patient patient = 1;</code>
     */
    public Builder addPatient(WarningService.Patient value) {
      if (patientBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePatientIsMutable();
        patient_.add(value);
        onChanged();
      } else {
        patientBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .WarningService.Patient patient = 1;</code>
     */
    public Builder addPatient(
        int index, WarningService.Patient value) {
      if (patientBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePatientIsMutable();
        patient_.add(index, value);
        onChanged();
      } else {
        patientBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .WarningService.Patient patient = 1;</code>
     */
    public Builder addPatient(
        WarningService.Patient.Builder builderForValue) {
      if (patientBuilder_ == null) {
        ensurePatientIsMutable();
        patient_.add(builderForValue.build());
        onChanged();
      } else {
        patientBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .WarningService.Patient patient = 1;</code>
     */
    public Builder addPatient(
        int index, WarningService.Patient.Builder builderForValue) {
      if (patientBuilder_ == null) {
        ensurePatientIsMutable();
        patient_.add(index, builderForValue.build());
        onChanged();
      } else {
        patientBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .WarningService.Patient patient = 1;</code>
     */
    public Builder addAllPatient(
        java.lang.Iterable<? extends WarningService.Patient> values) {
      if (patientBuilder_ == null) {
        ensurePatientIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, patient_);
        onChanged();
      } else {
        patientBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .WarningService.Patient patient = 1;</code>
     */
    public Builder clearPatient() {
      if (patientBuilder_ == null) {
        patient_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        patientBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .WarningService.Patient patient = 1;</code>
     */
    public Builder removePatient(int index) {
      if (patientBuilder_ == null) {
        ensurePatientIsMutable();
        patient_.remove(index);
        onChanged();
      } else {
        patientBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .WarningService.Patient patient = 1;</code>
     */
    public WarningService.Patient.Builder getPatientBuilder(
        int index) {
      return getPatientFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .WarningService.Patient patient = 1;</code>
     */
    public WarningService.PatientOrBuilder getPatientOrBuilder(
        int index) {
      if (patientBuilder_ == null) {
        return patient_.get(index);  } else {
        return patientBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .WarningService.Patient patient = 1;</code>
     */
    public java.util.List<? extends WarningService.PatientOrBuilder> 
         getPatientOrBuilderList() {
      if (patientBuilder_ != null) {
        return patientBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(patient_);
      }
    }
    /**
     * <code>repeated .WarningService.Patient patient = 1;</code>
     */
    public WarningService.Patient.Builder addPatientBuilder() {
      return getPatientFieldBuilder().addBuilder(
          WarningService.Patient.getDefaultInstance());
    }
    /**
     * <code>repeated .WarningService.Patient patient = 1;</code>
     */
    public WarningService.Patient.Builder addPatientBuilder(
        int index) {
      return getPatientFieldBuilder().addBuilder(
          index, WarningService.Patient.getDefaultInstance());
    }
    /**
     * <code>repeated .WarningService.Patient patient = 1;</code>
     */
    public java.util.List<WarningService.Patient.Builder> 
         getPatientBuilderList() {
      return getPatientFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        WarningService.Patient, WarningService.Patient.Builder, WarningService.PatientOrBuilder> 
        getPatientFieldBuilder() {
      if (patientBuilder_ == null) {
        patientBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            WarningService.Patient, WarningService.Patient.Builder, WarningService.PatientOrBuilder>(
                patient_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        patient_ = null;
      }
      return patientBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:WarningService.WarningServiceRequest)
  }

  // @@protoc_insertion_point(class_scope:WarningService.WarningServiceRequest)
  private static final WarningService.WarningServiceRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new WarningService.WarningServiceRequest();
  }

  public static WarningService.WarningServiceRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<WarningServiceRequest>
      PARSER = new com.google.protobuf.AbstractParser<WarningServiceRequest>() {
    @java.lang.Override
    public WarningServiceRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new WarningServiceRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<WarningServiceRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<WarningServiceRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public WarningService.WarningServiceRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

