// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WaringService.proto

package WarningService;

public interface WarningServiceResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WarningService.WarningServiceResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.WarningService.WarningServiceResponse.HealthStatus status = 3;</code>
   */
  int getStatusValue();
  /**
   * <code>.WarningService.WarningServiceResponse.HealthStatus status = 3;</code>
   */
  WarningService.WarningServiceResponse.HealthStatus getStatus();
}
