// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WarningService.proto

package WarningService;

/**
 * Protobuf type {@code WarningService.WarningServiceResponse}
 */
public  final class WarningServiceResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:WarningService.WarningServiceResponse)
    WarningServiceResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use WarningServiceResponse.newBuilder() to construct.
  private WarningServiceResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private WarningServiceResponse() {
    patientId_ = 0;
    riskLevel_ = 0;
    alert_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private WarningServiceResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            patientId_ = input.readInt32();
            break;
          }
          case 16: {

            riskLevel_ = input.readInt32();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            alert_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return WarningService.WarningServiceImpl.internal_static_WarningService_WarningServiceResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return WarningService.WarningServiceImpl.internal_static_WarningService_WarningServiceResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            WarningService.WarningServiceResponse.class, WarningService.WarningServiceResponse.Builder.class);
  }

  public static final int PATIENT_ID_FIELD_NUMBER = 1;
  private int patientId_;
  /**
   * <code>int32 patient_id = 1;</code>
   */
  public int getPatientId() {
    return patientId_;
  }

  public static final int RISK_LEVEL_FIELD_NUMBER = 2;
  private int riskLevel_;
  /**
   * <code>int32 risk_level = 2;</code>
   */
  public int getRiskLevel() {
    return riskLevel_;
  }

  public static final int ALERT_FIELD_NUMBER = 3;
  private volatile java.lang.Object alert_;
  /**
   * <code>string alert = 3;</code>
   */
  public java.lang.String getAlert() {
    java.lang.Object ref = alert_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      alert_ = s;
      return s;
    }
  }
  /**
   * <code>string alert = 3;</code>
   */
  public com.google.protobuf.ByteString
      getAlertBytes() {
    java.lang.Object ref = alert_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      alert_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (patientId_ != 0) {
      output.writeInt32(1, patientId_);
    }
    if (riskLevel_ != 0) {
      output.writeInt32(2, riskLevel_);
    }
    if (!getAlertBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, alert_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (patientId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, patientId_);
    }
    if (riskLevel_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, riskLevel_);
    }
    if (!getAlertBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, alert_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof WarningService.WarningServiceResponse)) {
      return super.equals(obj);
    }
    WarningService.WarningServiceResponse other = (WarningService.WarningServiceResponse) obj;

    boolean result = true;
    result = result && (getPatientId()
        == other.getPatientId());
    result = result && (getRiskLevel()
        == other.getRiskLevel());
    result = result && getAlert()
        .equals(other.getAlert());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PATIENT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getPatientId();
    hash = (37 * hash) + RISK_LEVEL_FIELD_NUMBER;
    hash = (53 * hash) + getRiskLevel();
    hash = (37 * hash) + ALERT_FIELD_NUMBER;
    hash = (53 * hash) + getAlert().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static WarningService.WarningServiceResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static WarningService.WarningServiceResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static WarningService.WarningServiceResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static WarningService.WarningServiceResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static WarningService.WarningServiceResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static WarningService.WarningServiceResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static WarningService.WarningServiceResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static WarningService.WarningServiceResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static WarningService.WarningServiceResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static WarningService.WarningServiceResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static WarningService.WarningServiceResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static WarningService.WarningServiceResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(WarningService.WarningServiceResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code WarningService.WarningServiceResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:WarningService.WarningServiceResponse)
      WarningService.WarningServiceResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return WarningService.WarningServiceImpl.internal_static_WarningService_WarningServiceResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return WarningService.WarningServiceImpl.internal_static_WarningService_WarningServiceResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              WarningService.WarningServiceResponse.class, WarningService.WarningServiceResponse.Builder.class);
    }

    // Construct using WarningService.WarningServiceResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      patientId_ = 0;

      riskLevel_ = 0;

      alert_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return WarningService.WarningServiceImpl.internal_static_WarningService_WarningServiceResponse_descriptor;
    }

    @java.lang.Override
    public WarningService.WarningServiceResponse getDefaultInstanceForType() {
      return WarningService.WarningServiceResponse.getDefaultInstance();
    }

    @java.lang.Override
    public WarningService.WarningServiceResponse build() {
      WarningService.WarningServiceResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public WarningService.WarningServiceResponse buildPartial() {
      WarningService.WarningServiceResponse result = new WarningService.WarningServiceResponse(this);
      result.patientId_ = patientId_;
      result.riskLevel_ = riskLevel_;
      result.alert_ = alert_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof WarningService.WarningServiceResponse) {
        return mergeFrom((WarningService.WarningServiceResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(WarningService.WarningServiceResponse other) {
      if (other == WarningService.WarningServiceResponse.getDefaultInstance()) return this;
      if (other.getPatientId() != 0) {
        setPatientId(other.getPatientId());
      }
      if (other.getRiskLevel() != 0) {
        setRiskLevel(other.getRiskLevel());
      }
      if (!other.getAlert().isEmpty()) {
        alert_ = other.alert_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      WarningService.WarningServiceResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (WarningService.WarningServiceResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int patientId_ ;
    /**
     * <code>int32 patient_id = 1;</code>
     */
    public int getPatientId() {
      return patientId_;
    }
    /**
     * <code>int32 patient_id = 1;</code>
     */
    public Builder setPatientId(int value) {
      
      patientId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 patient_id = 1;</code>
     */
    public Builder clearPatientId() {
      
      patientId_ = 0;
      onChanged();
      return this;
    }

    private int riskLevel_ ;
    /**
     * <code>int32 risk_level = 2;</code>
     */
    public int getRiskLevel() {
      return riskLevel_;
    }
    /**
     * <code>int32 risk_level = 2;</code>
     */
    public Builder setRiskLevel(int value) {
      
      riskLevel_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 risk_level = 2;</code>
     */
    public Builder clearRiskLevel() {
      
      riskLevel_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object alert_ = "";
    /**
     * <code>string alert = 3;</code>
     */
    public java.lang.String getAlert() {
      java.lang.Object ref = alert_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        alert_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string alert = 3;</code>
     */
    public com.google.protobuf.ByteString
        getAlertBytes() {
      java.lang.Object ref = alert_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        alert_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string alert = 3;</code>
     */
    public Builder setAlert(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      alert_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string alert = 3;</code>
     */
    public Builder clearAlert() {
      
      alert_ = getDefaultInstance().getAlert();
      onChanged();
      return this;
    }
    /**
     * <code>string alert = 3;</code>
     */
    public Builder setAlertBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      alert_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:WarningService.WarningServiceResponse)
  }

  // @@protoc_insertion_point(class_scope:WarningService.WarningServiceResponse)
  private static final WarningService.WarningServiceResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new WarningService.WarningServiceResponse();
  }

  public static WarningService.WarningServiceResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<WarningServiceResponse>
      PARSER = new com.google.protobuf.AbstractParser<WarningServiceResponse>() {
    @java.lang.Override
    public WarningServiceResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new WarningServiceResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<WarningServiceResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<WarningServiceResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public WarningService.WarningServiceResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

