// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WaringService.proto

package WarningService;

public final class WarningServiceImpl {
  private WarningServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WarningService_WarningServiceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WarningService_WarningServiceResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WarningService_Patient_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WarningService_Patient_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WarningService_WarningServiceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WarningService_WarningServiceRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023WaringService.proto\022\016WarningService\"\224\001" +
      "\n\026WarningServiceResponse\022C\n\006status\030\003 \001(\016" +
      "23.WarningService.WarningServiceResponse" +
      ".HealthStatus\"5\n\014HealthStatus\022\010\n\004GOOD\020\000\022" +
      "\014\n\010LOW_RISK\020\001\022\r\n\tHIGH_RISK\020\002\"6\n\007Patient\022" +
      "\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\021\n\triskLevel\030\003" +
      " \001(\005\"A\n\025WarningServiceRequest\022(\n\007patient" +
      "\030\001 \003(\0132\027.WarningService.Patient2l\n\016Warni" +
      "ngService\022Z\n\005Alert\022%.WarningService.Warn" +
      "ingServiceRequest\032&.WarningService.Warni" +
      "ngServiceResponse(\0010\001B\026B\022WarningServiceI" +
      "mplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_WarningService_WarningServiceResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_WarningService_WarningServiceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WarningService_WarningServiceResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_WarningService_Patient_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_WarningService_Patient_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WarningService_Patient_descriptor,
        new java.lang.String[] { "Id", "Name", "RiskLevel", });
    internal_static_WarningService_WarningServiceRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_WarningService_WarningServiceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WarningService_WarningServiceRequest_descriptor,
        new java.lang.String[] { "Patient", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
