// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WarningService.proto

package WarningService;

public interface WarningServiceResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WarningService.WarningServiceResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 patient_id = 1;</code>
   */
  int getPatientId();

  /**
   * <code>int32 risk_level = 2;</code>
   */
  int getRiskLevel();

  /**
   * <code>string alert = 3;</code>
   */
  java.lang.String getAlert();
  /**
   * <code>string alert = 3;</code>
   */
  com.google.protobuf.ByteString
      getAlertBytes();
}
