// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WarningService.proto

package WarningService;

public interface WarningServiceRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WarningService.WarningServiceRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 patient_id = 1;</code>
   */
  int getPatientId();
}
