// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: newMeasure.proto

package MeasureHR;

public final class heartRateImpl {
  private heartRateImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MeasureHR_rateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MeasureHR_rateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MeasureHR_rateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MeasureHR_rateResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MeasureHR_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MeasureHR_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020newMeasure.proto\022\tMeasureHR\".\n\013rateReq" +
      "uest\022\014\n\004name\030\001 \001(\t\022\021\n\tpatientID\030\002 \001(\005\"\033\n" +
      "\014rateResponse\022\013\n\003bpm\030\001 \001(\005\"\007\n\005Empty2O\n\013m" +
      "easureRate\022@\n\013displayRate\022\026.MeasureHR.ra" +
      "teRequest\032\027.MeasureHR.rateResponse\"\000B\021B\r" +
      "heartRateImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_MeasureHR_rateRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MeasureHR_rateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MeasureHR_rateRequest_descriptor,
        new java.lang.String[] { "Name", "PatientID", });
    internal_static_MeasureHR_rateResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_MeasureHR_rateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MeasureHR_rateResponse_descriptor,
        new java.lang.String[] { "Bpm", });
    internal_static_MeasureHR_Empty_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_MeasureHR_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MeasureHR_Empty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
