// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: newMeasure.proto

package MeasureHR;

public interface rateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MeasureHR.rateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 patientID = 2;</code>
   */
  int getPatientID();
}
