// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: newMeasure.proto

package MeasureHR;

public interface rateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MeasureHR.rateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 bpm = 1;</code>
   */
  int getBpm();
}
