// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: login.proto

package userLogin;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:user.Empty)
    com.google.protobuf.MessageOrBuilder {
}
