// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Heartmeasurement.proto

package HeartMeasurement;

public interface HeartMeasurementRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HeartMeasurement.HeartMeasurementRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .HeartMeasurement.Patient patient = 1;</code>
   */
  java.util.List<HeartMeasurement.Patient> 
      getPatientList();
  /**
   * <code>repeated .HeartMeasurement.Patient patient = 1;</code>
   */
  HeartMeasurement.Patient getPatient(int index);
  /**
   * <code>repeated .HeartMeasurement.Patient patient = 1;</code>
   */
  int getPatientCount();
  /**
   * <code>repeated .HeartMeasurement.Patient patient = 1;</code>
   */
  java.util.List<? extends HeartMeasurement.PatientOrBuilder> 
      getPatientOrBuilderList();
  /**
   * <code>repeated .HeartMeasurement.Patient patient = 1;</code>
   */
  HeartMeasurement.PatientOrBuilder getPatientOrBuilder(
      int index);
}
