// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Heartmeasurement.proto

package HeartMeasurement;

public interface HeartMeasurementResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HeartMeasurement.HeartMeasurementResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.HeartMeasurement.HeartMeasurementResponse.Status status = 3;</code>
   */
  int getStatusValue();
  /**
   * <code>.HeartMeasurement.HeartMeasurementResponse.Status status = 3;</code>
   */
  HeartMeasurement.HeartMeasurementResponse.Status getStatus();

  /**
   * <code>int32 bpm = 4;</code>
   */
  int getBpm();
}
