// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Heartmeasurement.proto

package HeartMeasurement;

public interface PatientOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HeartMeasurement.Patient)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 riskLevel = 3;</code>
   */
  int getRiskLevel();

  /**
   * <code>int32 bpm = 4;</code>
   */
  int getBpm();
}
