// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: heartbeat.proto

package HeartBeat;

public final class HeartBeatImpl {
  private HeartBeatImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HeartBeat_HeartbeatRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HeartBeat_HeartbeatRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HeartBeat_HeartbeatResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HeartBeat_HeartbeatResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017heartbeat.proto\022\tHeartBeat\"A\n\020Heartbea" +
      "tRequest\022\023\n\013currentRate\030\001 \001(\005\022\013\n\003min\030\002 \001" +
      "(\005\022\013\n\003max\030\003 \001(\005\"|\n\021HeartbeatResponse\0223\n\006" +
      "status\030\003 \001(\0162#.HeartBeat.HeartbeatRespon" +
      "se.Status\022\013\n\003bpm\030\004 \001(\005\"%\n\006Status\022\013\n\007FAIL" +
      "URE\020\000\022\016\n\nSUCCESSFUL\020\0012\226\001\n\tHeartBeat\022D\n\007G" +
      "etRate\022\033.HeartBeat.HeartbeatRequest\032\034.He" +
      "artBeat.HeartbeatResponse\022C\n\006fixBug\022\033.He" +
      "artBeat.HeartbeatRequest\032\034.HeartBeat.Hea" +
      "rtbeatResponseB\021B\rHeartBeatImplP\001b\006proto" +
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_HeartBeat_HeartbeatRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_HeartBeat_HeartbeatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HeartBeat_HeartbeatRequest_descriptor,
        new java.lang.String[] { "CurrentRate", "Min", "Max", });
    internal_static_HeartBeat_HeartbeatResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_HeartBeat_HeartbeatResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HeartBeat_HeartbeatResponse_descriptor,
        new java.lang.String[] { "Status", "Bpm", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
