// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: heartbeat.proto

package HeartBeat;

public interface HeartbeatResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HeartBeat.HeartbeatResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.HeartBeat.HeartbeatResponse.Status status = 1;</code>
   */
  int getStatusValue();
  /**
   * <code>.HeartBeat.HeartbeatResponse.Status status = 1;</code>
   */
  HeartBeat.HeartbeatResponse.Status getStatus();

  /**
   * <code>int32 bpm = 2;</code>
   */
  int getBpm();
}
