// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: heartbeat.proto

package HeartBeat;

public final class HeartBeatImpl {
  private HeartBeatImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HeartBeat_HeartbeatRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HeartBeat_HeartbeatRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HeartBeat_HeartbeatResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HeartBeat_HeartbeatResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017heartbeat.proto\022\tHeartBeat\"%\n\020Heartbea" +
      "tRequest\022\021\n\tpatientId\030\001 \001(\005\"|\n\021Heartbeat" +
      "Response\0223\n\006status\030\001 \001(\0162#.HeartBeat.Hea" +
      "rtbeatResponse.Status\022\013\n\003bpm\030\002 \001(\005\"%\n\006St" +
      "atus\022\013\n\007FAILURE\020\000\022\016\n\nSUCCESSFUL\020\0012Q\n\tHea" +
      "rtBeat\022D\n\007getRate\022\033.HeartBeat.HeartbeatR" +
      "equest\032\034.HeartBeat.HeartbeatResponseB\021B\r" +
      "HeartBeatImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_HeartBeat_HeartbeatRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_HeartBeat_HeartbeatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HeartBeat_HeartbeatRequest_descriptor,
        new java.lang.String[] { "PatientId", });
    internal_static_HeartBeat_HeartbeatResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_HeartBeat_HeartbeatResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HeartBeat_HeartbeatResponse_descriptor,
        new java.lang.String[] { "Status", "Bpm", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
