// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: heartbeat.proto

package HeartBeat;

public interface HeartbeatRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HeartBeat.HeartbeatRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 currentRate = 1;</code>
   */
  int getCurrentRate();

  /**
   * <code>int32 min = 2;</code>
   */
  int getMin();

  /**
   * <code>int32 max = 3;</code>
   */
  int getMax();
}
