// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RecordingService.proto

package RecordingsSerive;

public interface MedicalRecordOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RecordingsSerive.MedicalRecord)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string DoctorName = 3;</code>
   */
  java.lang.String getDoctorName();
  /**
   * <code>string DoctorName = 3;</code>
   */
  com.google.protobuf.ByteString
      getDoctorNameBytes();
}
