// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RecordingService.proto

package RecordingsSerive;

public final class RecordServiceImpl {
  private RecordServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RecordingsSerive_RecordingServiceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RecordingsSerive_RecordingServiceResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RecordingsSerive_MedicalRecord_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RecordingsSerive_MedicalRecord_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RecordingsSerive_Patient_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RecordingsSerive_Patient_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RecordingsSerive_RecordingServiceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RecordingsSerive_RecordingServiceRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026RecordingService.proto\022\020RecordingsSeri" +
      "ve\"\275\001\n\030RecordingServiceResponse\022A\n\006statu" +
      "s\030\003 \001(\01621.RecordingsSerive.RecordingServ" +
      "iceResponse.Status\0227\n\016medicalRecords\030\004 \003" +
      "(\0132\037.RecordingsSerive.MedicalRecord\"%\n\006S" +
      "tatus\022\013\n\007FAILURE\020\000\022\016\n\nSUCCESSFUL\020\001\"=\n\rMe" +
      "dicalRecord\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\022\n" +
      "\nDoctorName\030\003 \001(\t\"6\n\007Patient\022\n\n\002id\030\001 \001(\005" +
      "\022\014\n\004name\030\002 \001(\t\022\021\n\triskLevel\030\003 \001(\005\"E\n\027Rec" +
      "ordingServiceRequest\022*\n\007patient\030\001 \003(\0132\031." +
      "RecordingsSerive.Patient2\205\001\n\020RecordingSe" +
      "rvice\022q\n\026RecordRecordingService\022).Record" +
      "ingsSerive.RecordingServiceRequest\032*.Rec" +
      "ordingsSerive.RecordingServiceResponse(\001" +
      "B\025B\021RecordServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_RecordingsSerive_RecordingServiceResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RecordingsSerive_RecordingServiceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RecordingsSerive_RecordingServiceResponse_descriptor,
        new java.lang.String[] { "Status", "MedicalRecords", });
    internal_static_RecordingsSerive_MedicalRecord_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_RecordingsSerive_MedicalRecord_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RecordingsSerive_MedicalRecord_descriptor,
        new java.lang.String[] { "Id", "Name", "DoctorName", });
    internal_static_RecordingsSerive_Patient_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_RecordingsSerive_Patient_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RecordingsSerive_Patient_descriptor,
        new java.lang.String[] { "Id", "Name", "RiskLevel", });
    internal_static_RecordingsSerive_RecordingServiceRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_RecordingsSerive_RecordingServiceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RecordingsSerive_RecordingServiceRequest_descriptor,
        new java.lang.String[] { "Patient", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
