// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RecordingService.proto

package RecordingsSerive;

public interface RecordingServiceRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RecordingsSerive.RecordingServiceRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *take risk level from patient
   * </pre>
   *
   * <code>repeated .RecordingsSerive.Patient patient = 1;</code>
   */
  java.util.List<RecordingsSerive.Patient> 
      getPatientList();
  /**
   * <pre>
   *take risk level from patient
   * </pre>
   *
   * <code>repeated .RecordingsSerive.Patient patient = 1;</code>
   */
  RecordingsSerive.Patient getPatient(int index);
  /**
   * <pre>
   *take risk level from patient
   * </pre>
   *
   * <code>repeated .RecordingsSerive.Patient patient = 1;</code>
   */
  int getPatientCount();
  /**
   * <pre>
   *take risk level from patient
   * </pre>
   *
   * <code>repeated .RecordingsSerive.Patient patient = 1;</code>
   */
  java.util.List<? extends RecordingsSerive.PatientOrBuilder> 
      getPatientOrBuilderList();
  /**
   * <pre>
   *take risk level from patient
   * </pre>
   *
   * <code>repeated .RecordingsSerive.Patient patient = 1;</code>
   */
  RecordingsSerive.PatientOrBuilder getPatientOrBuilder(
      int index);
}
