// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RecordingService.proto

package RecordingsSerive;

public interface RecordingServiceResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RecordingsSerive.RecordingServiceResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.RecordingsSerive.RecordingServiceResponse.Status status = 3;</code>
   */
  int getStatusValue();
  /**
   * <code>.RecordingsSerive.RecordingServiceResponse.Status status = 3;</code>
   */
  RecordingsSerive.RecordingServiceResponse.Status getStatus();

  /**
   * <pre>
   *list medical records
   * </pre>
   *
   * <code>repeated .RecordingsSerive.MedicalRecord medicalRecords = 4;</code>
   */
  java.util.List<RecordingsSerive.MedicalRecord> 
      getMedicalRecordsList();
  /**
   * <pre>
   *list medical records
   * </pre>
   *
   * <code>repeated .RecordingsSerive.MedicalRecord medicalRecords = 4;</code>
   */
  RecordingsSerive.MedicalRecord getMedicalRecords(int index);
  /**
   * <pre>
   *list medical records
   * </pre>
   *
   * <code>repeated .RecordingsSerive.MedicalRecord medicalRecords = 4;</code>
   */
  int getMedicalRecordsCount();
  /**
   * <pre>
   *list medical records
   * </pre>
   *
   * <code>repeated .RecordingsSerive.MedicalRecord medicalRecords = 4;</code>
   */
  java.util.List<? extends RecordingsSerive.MedicalRecordOrBuilder> 
      getMedicalRecordsOrBuilderList();
  /**
   * <pre>
   *list medical records
   * </pre>
   *
   * <code>repeated .RecordingsSerive.MedicalRecord medicalRecords = 4;</code>
   */
  RecordingsSerive.MedicalRecordOrBuilder getMedicalRecordsOrBuilder(
      int index);
}
