// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WaringService.proto

package WarningSerive;

public interface WarningServiceResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WarningSerive.WarningServiceResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.WarningSerive.WarningServiceResponse.HealthStatus status = 3;</code>
   */
  int getStatusValue();
  /**
   * <code>.WarningSerive.WarningServiceResponse.HealthStatus status = 3;</code>
   */
  WarningSerive.WarningServiceResponse.HealthStatus getStatus();
}
