// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WaringService.proto

package WarningSerive;

public interface WarningServiceRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WarningSerive.WarningServiceRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .WarningSerive.Patient patient = 1;</code>
   */
  java.util.List<WarningSerive.Patient> 
      getPatientList();
  /**
   * <code>repeated .WarningSerive.Patient patient = 1;</code>
   */
  WarningSerive.Patient getPatient(int index);
  /**
   * <code>repeated .WarningSerive.Patient patient = 1;</code>
   */
  int getPatientCount();
  /**
   * <code>repeated .WarningSerive.Patient patient = 1;</code>
   */
  java.util.List<? extends WarningSerive.PatientOrBuilder> 
      getPatientOrBuilderList();
  /**
   * <code>repeated .WarningSerive.Patient patient = 1;</code>
   */
  WarningSerive.PatientOrBuilder getPatientOrBuilder(
      int index);
}
