// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RecordingService.proto

package RecordingService;

/**
 * Protobuf type {@code RecordingService.MedicalRecordResponse}
 */
public  final class MedicalRecordResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:RecordingService.MedicalRecordResponse)
    MedicalRecordResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MedicalRecordResponse.newBuilder() to construct.
  private MedicalRecordResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MedicalRecordResponse() {
    status_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MedicalRecordResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            status_ = rawValue;
            break;
          }
          case 18: {
            RecordingService.MedicalRecord.Builder subBuilder = null;
            if (medicalRecord_ != null) {
              subBuilder = medicalRecord_.toBuilder();
            }
            medicalRecord_ = input.readMessage(RecordingService.MedicalRecord.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(medicalRecord_);
              medicalRecord_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return RecordingService.RecordServiceImpl.internal_static_RecordingService_MedicalRecordResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return RecordingService.RecordServiceImpl.internal_static_RecordingService_MedicalRecordResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            RecordingService.MedicalRecordResponse.class, RecordingService.MedicalRecordResponse.Builder.class);
  }

  /**
   * Protobuf enum {@code RecordingService.MedicalRecordResponse.Status}
   */
  public enum Status
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>FAILURE = 0;</code>
     */
    FAILURE(0),
    /**
     * <code>SUCCESSFUL = 1;</code>
     */
    SUCCESSFUL(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>FAILURE = 0;</code>
     */
    public static final int FAILURE_VALUE = 0;
    /**
     * <code>SUCCESSFUL = 1;</code>
     */
    public static final int SUCCESSFUL_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Status valueOf(int value) {
      return forNumber(value);
    }

    public static Status forNumber(int value) {
      switch (value) {
        case 0: return FAILURE;
        case 1: return SUCCESSFUL;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Status>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Status> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Status>() {
            public Status findValueByNumber(int number) {
              return Status.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return RecordingService.MedicalRecordResponse.getDescriptor().getEnumTypes().get(0);
    }

    private static final Status[] VALUES = values();

    public static Status valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Status(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:RecordingService.MedicalRecordResponse.Status)
  }

  public static final int STATUS_FIELD_NUMBER = 1;
  private int status_;
  /**
   * <code>.RecordingService.MedicalRecordResponse.Status status = 1;</code>
   */
  public int getStatusValue() {
    return status_;
  }
  /**
   * <code>.RecordingService.MedicalRecordResponse.Status status = 1;</code>
   */
  public RecordingService.MedicalRecordResponse.Status getStatus() {
    @SuppressWarnings("deprecation")
    RecordingService.MedicalRecordResponse.Status result = RecordingService.MedicalRecordResponse.Status.valueOf(status_);
    return result == null ? RecordingService.MedicalRecordResponse.Status.UNRECOGNIZED : result;
  }

  public static final int MEDICALRECORD_FIELD_NUMBER = 2;
  private RecordingService.MedicalRecord medicalRecord_;
  /**
   * <pre>
   *list medical records
   * </pre>
   *
   * <code>.RecordingService.MedicalRecord medicalRecord = 2;</code>
   */
  public boolean hasMedicalRecord() {
    return medicalRecord_ != null;
  }
  /**
   * <pre>
   *list medical records
   * </pre>
   *
   * <code>.RecordingService.MedicalRecord medicalRecord = 2;</code>
   */
  public RecordingService.MedicalRecord getMedicalRecord() {
    return medicalRecord_ == null ? RecordingService.MedicalRecord.getDefaultInstance() : medicalRecord_;
  }
  /**
   * <pre>
   *list medical records
   * </pre>
   *
   * <code>.RecordingService.MedicalRecord medicalRecord = 2;</code>
   */
  public RecordingService.MedicalRecordOrBuilder getMedicalRecordOrBuilder() {
    return getMedicalRecord();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (status_ != RecordingService.MedicalRecordResponse.Status.FAILURE.getNumber()) {
      output.writeEnum(1, status_);
    }
    if (medicalRecord_ != null) {
      output.writeMessage(2, getMedicalRecord());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (status_ != RecordingService.MedicalRecordResponse.Status.FAILURE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, status_);
    }
    if (medicalRecord_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getMedicalRecord());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof RecordingService.MedicalRecordResponse)) {
      return super.equals(obj);
    }
    RecordingService.MedicalRecordResponse other = (RecordingService.MedicalRecordResponse) obj;

    boolean result = true;
    result = result && status_ == other.status_;
    result = result && (hasMedicalRecord() == other.hasMedicalRecord());
    if (hasMedicalRecord()) {
      result = result && getMedicalRecord()
          .equals(other.getMedicalRecord());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + status_;
    if (hasMedicalRecord()) {
      hash = (37 * hash) + MEDICALRECORD_FIELD_NUMBER;
      hash = (53 * hash) + getMedicalRecord().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static RecordingService.MedicalRecordResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static RecordingService.MedicalRecordResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static RecordingService.MedicalRecordResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static RecordingService.MedicalRecordResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static RecordingService.MedicalRecordResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static RecordingService.MedicalRecordResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static RecordingService.MedicalRecordResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static RecordingService.MedicalRecordResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static RecordingService.MedicalRecordResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static RecordingService.MedicalRecordResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static RecordingService.MedicalRecordResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static RecordingService.MedicalRecordResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(RecordingService.MedicalRecordResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code RecordingService.MedicalRecordResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:RecordingService.MedicalRecordResponse)
      RecordingService.MedicalRecordResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RecordingService.RecordServiceImpl.internal_static_RecordingService_MedicalRecordResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RecordingService.RecordServiceImpl.internal_static_RecordingService_MedicalRecordResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RecordingService.MedicalRecordResponse.class, RecordingService.MedicalRecordResponse.Builder.class);
    }

    // Construct using RecordingService.MedicalRecordResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      status_ = 0;

      if (medicalRecordBuilder_ == null) {
        medicalRecord_ = null;
      } else {
        medicalRecord_ = null;
        medicalRecordBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return RecordingService.RecordServiceImpl.internal_static_RecordingService_MedicalRecordResponse_descriptor;
    }

    @java.lang.Override
    public RecordingService.MedicalRecordResponse getDefaultInstanceForType() {
      return RecordingService.MedicalRecordResponse.getDefaultInstance();
    }

    @java.lang.Override
    public RecordingService.MedicalRecordResponse build() {
      RecordingService.MedicalRecordResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public RecordingService.MedicalRecordResponse buildPartial() {
      RecordingService.MedicalRecordResponse result = new RecordingService.MedicalRecordResponse(this);
      result.status_ = status_;
      if (medicalRecordBuilder_ == null) {
        result.medicalRecord_ = medicalRecord_;
      } else {
        result.medicalRecord_ = medicalRecordBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof RecordingService.MedicalRecordResponse) {
        return mergeFrom((RecordingService.MedicalRecordResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(RecordingService.MedicalRecordResponse other) {
      if (other == RecordingService.MedicalRecordResponse.getDefaultInstance()) return this;
      if (other.status_ != 0) {
        setStatusValue(other.getStatusValue());
      }
      if (other.hasMedicalRecord()) {
        mergeMedicalRecord(other.getMedicalRecord());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      RecordingService.MedicalRecordResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (RecordingService.MedicalRecordResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int status_ = 0;
    /**
     * <code>.RecordingService.MedicalRecordResponse.Status status = 1;</code>
     */
    public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.RecordingService.MedicalRecordResponse.Status status = 1;</code>
     */
    public Builder setStatusValue(int value) {
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.RecordingService.MedicalRecordResponse.Status status = 1;</code>
     */
    public RecordingService.MedicalRecordResponse.Status getStatus() {
      @SuppressWarnings("deprecation")
      RecordingService.MedicalRecordResponse.Status result = RecordingService.MedicalRecordResponse.Status.valueOf(status_);
      return result == null ? RecordingService.MedicalRecordResponse.Status.UNRECOGNIZED : result;
    }
    /**
     * <code>.RecordingService.MedicalRecordResponse.Status status = 1;</code>
     */
    public Builder setStatus(RecordingService.MedicalRecordResponse.Status value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      status_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.RecordingService.MedicalRecordResponse.Status status = 1;</code>
     */
    public Builder clearStatus() {
      
      status_ = 0;
      onChanged();
      return this;
    }

    private RecordingService.MedicalRecord medicalRecord_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        RecordingService.MedicalRecord, RecordingService.MedicalRecord.Builder, RecordingService.MedicalRecordOrBuilder> medicalRecordBuilder_;
    /**
     * <pre>
     *list medical records
     * </pre>
     *
     * <code>.RecordingService.MedicalRecord medicalRecord = 2;</code>
     */
    public boolean hasMedicalRecord() {
      return medicalRecordBuilder_ != null || medicalRecord_ != null;
    }
    /**
     * <pre>
     *list medical records
     * </pre>
     *
     * <code>.RecordingService.MedicalRecord medicalRecord = 2;</code>
     */
    public RecordingService.MedicalRecord getMedicalRecord() {
      if (medicalRecordBuilder_ == null) {
        return medicalRecord_ == null ? RecordingService.MedicalRecord.getDefaultInstance() : medicalRecord_;
      } else {
        return medicalRecordBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     *list medical records
     * </pre>
     *
     * <code>.RecordingService.MedicalRecord medicalRecord = 2;</code>
     */
    public Builder setMedicalRecord(RecordingService.MedicalRecord value) {
      if (medicalRecordBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        medicalRecord_ = value;
        onChanged();
      } else {
        medicalRecordBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     *list medical records
     * </pre>
     *
     * <code>.RecordingService.MedicalRecord medicalRecord = 2;</code>
     */
    public Builder setMedicalRecord(
        RecordingService.MedicalRecord.Builder builderForValue) {
      if (medicalRecordBuilder_ == null) {
        medicalRecord_ = builderForValue.build();
        onChanged();
      } else {
        medicalRecordBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     *list medical records
     * </pre>
     *
     * <code>.RecordingService.MedicalRecord medicalRecord = 2;</code>
     */
    public Builder mergeMedicalRecord(RecordingService.MedicalRecord value) {
      if (medicalRecordBuilder_ == null) {
        if (medicalRecord_ != null) {
          medicalRecord_ =
            RecordingService.MedicalRecord.newBuilder(medicalRecord_).mergeFrom(value).buildPartial();
        } else {
          medicalRecord_ = value;
        }
        onChanged();
      } else {
        medicalRecordBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     *list medical records
     * </pre>
     *
     * <code>.RecordingService.MedicalRecord medicalRecord = 2;</code>
     */
    public Builder clearMedicalRecord() {
      if (medicalRecordBuilder_ == null) {
        medicalRecord_ = null;
        onChanged();
      } else {
        medicalRecord_ = null;
        medicalRecordBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     *list medical records
     * </pre>
     *
     * <code>.RecordingService.MedicalRecord medicalRecord = 2;</code>
     */
    public RecordingService.MedicalRecord.Builder getMedicalRecordBuilder() {
      
      onChanged();
      return getMedicalRecordFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *list medical records
     * </pre>
     *
     * <code>.RecordingService.MedicalRecord medicalRecord = 2;</code>
     */
    public RecordingService.MedicalRecordOrBuilder getMedicalRecordOrBuilder() {
      if (medicalRecordBuilder_ != null) {
        return medicalRecordBuilder_.getMessageOrBuilder();
      } else {
        return medicalRecord_ == null ?
            RecordingService.MedicalRecord.getDefaultInstance() : medicalRecord_;
      }
    }
    /**
     * <pre>
     *list medical records
     * </pre>
     *
     * <code>.RecordingService.MedicalRecord medicalRecord = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        RecordingService.MedicalRecord, RecordingService.MedicalRecord.Builder, RecordingService.MedicalRecordOrBuilder> 
        getMedicalRecordFieldBuilder() {
      if (medicalRecordBuilder_ == null) {
        medicalRecordBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            RecordingService.MedicalRecord, RecordingService.MedicalRecord.Builder, RecordingService.MedicalRecordOrBuilder>(
                getMedicalRecord(),
                getParentForChildren(),
                isClean());
        medicalRecord_ = null;
      }
      return medicalRecordBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:RecordingService.MedicalRecordResponse)
  }

  // @@protoc_insertion_point(class_scope:RecordingService.MedicalRecordResponse)
  private static final RecordingService.MedicalRecordResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new RecordingService.MedicalRecordResponse();
  }

  public static RecordingService.MedicalRecordResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MedicalRecordResponse>
      PARSER = new com.google.protobuf.AbstractParser<MedicalRecordResponse>() {
    @java.lang.Override
    public MedicalRecordResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MedicalRecordResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MedicalRecordResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MedicalRecordResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public RecordingService.MedicalRecordResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

