// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RecordingService.proto

package RecordingService;

public interface MedicalRecordRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RecordingService.MedicalRecordRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *take risk level from patient
   * </pre>
   *
   * <code>repeated .RecordingService.Patient patient = 1;</code>
   */
  java.util.List<RecordingService.Patient> 
      getPatientList();
  /**
   * <pre>
   *take risk level from patient
   * </pre>
   *
   * <code>repeated .RecordingService.Patient patient = 1;</code>
   */
  RecordingService.Patient getPatient(int index);
  /**
   * <pre>
   *take risk level from patient
   * </pre>
   *
   * <code>repeated .RecordingService.Patient patient = 1;</code>
   */
  int getPatientCount();
  /**
   * <pre>
   *take risk level from patient
   * </pre>
   *
   * <code>repeated .RecordingService.Patient patient = 1;</code>
   */
  java.util.List<? extends RecordingService.PatientOrBuilder> 
      getPatientOrBuilderList();
  /**
   * <pre>
   *take risk level from patient
   * </pre>
   *
   * <code>repeated .RecordingService.Patient patient = 1;</code>
   */
  RecordingService.PatientOrBuilder getPatientOrBuilder(
      int index);
}
