// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RecordingService.proto

package RecordingService;

public interface MedicalRecordRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RecordingService.MedicalRecordRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated int32 ids = 1;</code>
   */
  java.util.List<java.lang.Integer> getIdsList();
  /**
   * <code>repeated int32 ids = 1;</code>
   */
  int getIdsCount();
  /**
   * <code>repeated int32 ids = 1;</code>
   */
  int getIds(int index);
}
