// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RecordingService.proto

package RecordingService;

public interface PatientRecordsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RecordingService.PatientRecordsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 riskLevel = 2;</code>
   */
  int getRiskLevel();
}
