// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RecordingService.proto

package RecordingService;

public interface PatientResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RecordingService.PatientResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.RecordingService.Patient patient = 2;</code>
   */
  boolean hasPatient();
  /**
   * <code>.RecordingService.Patient patient = 2;</code>
   */
  RecordingService.Patient getPatient();
  /**
   * <code>.RecordingService.Patient patient = 2;</code>
   */
  RecordingService.PatientOrBuilder getPatientOrBuilder();
}
