// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RecordingService.proto

package RecordingService;

public interface PatientRecordsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RecordingService.PatientRecordsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();
}
