// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RecordingService.proto

package RecordingService;

public interface PatientRecordsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RecordingService.PatientRecordsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 min_bpm = 1;</code>
   */
  int getMinBpm();

  /**
   * <code>int32 max_bpm = 2;</code>
   */
  int getMaxBpm();
}
