// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RecordingService.proto

package RecordingService;

public final class RecordServiceImpl {
  private RecordServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RecordingService_MedicalRecordResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RecordingService_MedicalRecordResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RecordingService_MedicalRecord_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RecordingService_MedicalRecord_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RecordingService_Patient_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RecordingService_Patient_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RecordingService_PatientRecordsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RecordingService_PatientRecordsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RecordingService_PatientRecordsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RecordingService_PatientRecordsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RecordingService_MedicalRecordRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RecordingService_MedicalRecordRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RecordingService_SetPatientBpmRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RecordingService_SetPatientBpmRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RecordingService_PatientResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RecordingService_PatientResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026RecordingService.proto\022\020RecordingServi" +
      "ce\"\267\001\n\025MedicalRecordResponse\022>\n\006status\030\003" +
      " \001(\0162..RecordingService.MedicalRecordRes" +
      "ponse.Status\0227\n\016medicalRecords\030\004 \003(\0132\037.R" +
      "ecordingService.MedicalRecord\"%\n\006Status\022" +
      "\013\n\007FAILURE\020\000\022\016\n\nSUCCESSFUL\020\001\"=\n\rMedicalR" +
      "ecord\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\022\n\nDocto" +
      "rName\030\003 \001(\t\"C\n\007Patient\022\n\n\002id\030\001 \001(\005\022\014\n\004na" +
      "me\030\002 \001(\t\022\021\n\triskLevel\030\003 \001(\005\022\013\n\003bpm\030\004 \001(\005" +
      "\"#\n\025PatientRecordsRequest\022\n\n\002id\030\001 \001(\005\"+\n" +
      "\026PatientRecordsResponse\022\021\n\triskLevel\030\002 \001" +
      "(\005\"B\n\024MedicalRecordRequest\022*\n\007patient\030\001 " +
      "\003(\0132\031.RecordingService.Patient\"/\n\024SetPat" +
      "ientBpmRequest\022\013\n\003bpm\030\001 \001(\005\022\n\n\002id\030\002 \001(\005\"" +
      "=\n\017PatientResponse\022*\n\007patient\030\002 \001(\0132\031.Re" +
      "cordingService.Patient2\271\002\n\020RecordingServ" +
      "ice\022f\n\021getMedicalRecords\022&.RecordingServ" +
      "ice.MedicalRecordRequest\032\'.RecordingServ" +
      "ice.MedicalRecordResponse0\001\022h\n\021getPatien" +
      "tRecords\022\'.RecordingService.PatientRecor" +
      "dsRequest\032(.RecordingService.PatientReco" +
      "rdsResponse0\001\022S\n\006setBpm\022&.RecordingServi" +
      "ce.SetPatientBpmRequest\032!.RecordingServi" +
      "ce.PatientResponseB\025B\021RecordServiceImplP" +
      "\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_RecordingService_MedicalRecordResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RecordingService_MedicalRecordResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RecordingService_MedicalRecordResponse_descriptor,
        new java.lang.String[] { "Status", "MedicalRecords", });
    internal_static_RecordingService_MedicalRecord_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_RecordingService_MedicalRecord_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RecordingService_MedicalRecord_descriptor,
        new java.lang.String[] { "Id", "Name", "DoctorName", });
    internal_static_RecordingService_Patient_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_RecordingService_Patient_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RecordingService_Patient_descriptor,
        new java.lang.String[] { "Id", "Name", "RiskLevel", "Bpm", });
    internal_static_RecordingService_PatientRecordsRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_RecordingService_PatientRecordsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RecordingService_PatientRecordsRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_RecordingService_PatientRecordsResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_RecordingService_PatientRecordsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RecordingService_PatientRecordsResponse_descriptor,
        new java.lang.String[] { "RiskLevel", });
    internal_static_RecordingService_MedicalRecordRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_RecordingService_MedicalRecordRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RecordingService_MedicalRecordRequest_descriptor,
        new java.lang.String[] { "Patient", });
    internal_static_RecordingService_SetPatientBpmRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_RecordingService_SetPatientBpmRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RecordingService_SetPatientBpmRequest_descriptor,
        new java.lang.String[] { "Bpm", "Id", });
    internal_static_RecordingService_PatientResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_RecordingService_PatientResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RecordingService_PatientResponse_descriptor,
        new java.lang.String[] { "Patient", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
