// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RecordingService.proto

package RecordingService;

public interface SetPatientBpmRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RecordingService.SetPatientBpmRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 bpm = 1;</code>
   */
  int getBpm();

  /**
   * <code>int32 id = 2;</code>
   */
  int getId();
}
